export const mockData = {
  deliveryAddress: {
    name: "Aut quis veritatis q",
    address: "P 16 Krishan Vihar, mc",
    postTown: "South",
    county: "Delhi",
    postCode: "110045",
    country: "GB",
    telephone: "83972732873",
    email: "huge@mailinator.com",
  },
  invoiceAddress: {
    name: "Illo consectetur in",
    address: "Adipisicing doloremq",
    postTown: "Quisquam deserunt de",
    county: "Perspiciatis quis p",
    postCode: "Recusandae Repellen",
    country: "GB",
    telephone: "9354697528",
    email: "qaxevecyg@mailinator.com",
  },
  productDetails: {
    name: "Anvil Tulsa Gibson Safety Shoe",
    code: "SS006",
    image: "/path-to-image.jpg",
  },
  orderTotals: {
    quantity: 1,
    subTotal: "£58.50",
    artworkSetup: "£0.00",
    carriage: "£4.95",
    totalVAT: "£11.70",
    total: "£75.15",
  },
};
