import Link from "next/link";

export default function Page() {
  return (
    <div className="pt-[10vh] md:pt-[15vh]">
      <div className="max-w-9xl mx-auto p-4 md:p-6 lg:p-20 bg-white">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="mb-4 text-sm text-gray-500">
          Last updated: October 04, 2024
        </p>

        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mb-6">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You are agreeing to the terms and conditions.
        </p>

        <h2 className="text-2xl font-semibold mb-4">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-semibold mb-3">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="text-xl font-semibold mb-3">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside mb-6">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Volvrit - IT Service Company, No - 9 Plot,
            Building, 2nd, 3rd and 4th Floor, 1, Moti Nagar Rd, DLE Industrial
            Area, New Delhi, Delhi 110015.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </li>
          <li>
            <strong>Country</strong> refers to: Delhi, India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cell phone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Third-party social media Service</strong> refers to any
            website or social network website through which a User can log in or
            create an account to use the Service.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website</strong> refers to Volvrit - IT Service Company,
            accessible from https://volvrit.com/
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mb-4">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="text-xl font-semibold mb-3">Types of Data Collected</h3>

        <h4 className="text-lg font-medium mb-2">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, we may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="list-disc list-inside mb-6">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-medium mb-2">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service. This may
          include details such as your IP address, browser type, browser
          version, and diagnostic data.
        </p>

        {/* Add more sections as per the Privacy Policy */}
        <p className="mb-4">
          For more details about how we handle and protect your data, please
          visit our full Privacy Policy page.
        </p>

        <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul className="list-disc list-inside mb-6">
          <li>By email: info@volvrit.com</li>
          <li>
            By visiting this page on our website:{" "}
            <Link
              aria-label="contact Us"
              href="https://volvrit.com/contact-us"
              className="text-blue-600 hover:underline"
            >
              https://volvrit.com/contact-us
            </Link>
          </li>
        </ul>
      </div>
    </div>
  );
}
